apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1
  namespace: default
spec:
  selector:
    matchLabels:
      app: deploy-1
  template:
    metadata:
      labels:
        app: deploy-1
    spec:
      containers:
      - name: pod-1
        image: alpine
        command: ["sh", "-c", "touch -a /data/storefile.txt; while true; do echo $(( `cat /data/storefile.txt` + 1)) > /data/storefile.txt; cat /data/storefile.txt; sleep 1; done;"]
        volumeMounts:
        - mountPath: /data
          name: local-data
      volumes:
      - name: local-data
        persistentVolumeClaim:
          claimName: base-claim
